"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.castleController = exports.marketController = exports.clanController = exports.worldsController = exports.battleController = exports.marchingController = exports.enemyController = exports.trainningController = exports.upgradeController = exports.unitController = exports.buildingController = exports.resourceController = exports.userController = exports.authController = void 0;
var authController_1 = require("./authController");
Object.defineProperty(exports, "authController", { enumerable: true, get: function () { return authController_1.default; } });
var userController_1 = require("./userController");
Object.defineProperty(exports, "userController", { enumerable: true, get: function () { return userController_1.default; } });
var resourceController_1 = require("./resourceController");
Object.defineProperty(exports, "resourceController", { enumerable: true, get: function () { return resourceController_1.default; } });
var buildingController_1 = require("./buildingController");
Object.defineProperty(exports, "buildingController", { enumerable: true, get: function () { return buildingController_1.default; } });
var unitController_1 = require("./unitController");
Object.defineProperty(exports, "unitController", { enumerable: true, get: function () { return unitController_1.default; } });
var upgradeController_1 = require("./upgradeController");
Object.defineProperty(exports, "upgradeController", { enumerable: true, get: function () { return upgradeController_1.default; } });
var trainningController_1 = require("./trainningController");
Object.defineProperty(exports, "trainningController", { enumerable: true, get: function () { return trainningController_1.default; } });
var enemyController_1 = require("./enemyController");
Object.defineProperty(exports, "enemyController", { enumerable: true, get: function () { return enemyController_1.default; } });
var marchingController_1 = require("./marchingController");
Object.defineProperty(exports, "marchingController", { enumerable: true, get: function () { return marchingController_1.default; } });
var battleController_1 = require("./battleController");
Object.defineProperty(exports, "battleController", { enumerable: true, get: function () { return battleController_1.default; } });
var worldsController_1 = require("./worldsController");
Object.defineProperty(exports, "worldsController", { enumerable: true, get: function () { return worldsController_1.default; } });
var clanController_1 = require("./clanController");
Object.defineProperty(exports, "clanController", { enumerable: true, get: function () { return clanController_1.default; } });
var marketController_1 = require("./marketController");
Object.defineProperty(exports, "marketController", { enumerable: true, get: function () { return marketController_1.default; } });
var castleController_1 = require("./castleController");
Object.defineProperty(exports, "castleController", { enumerable: true, get: function () { return castleController_1.default; } });
//# sourceMappingURL=index.js.map