"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.castleController = exports.marketController = exports.clanController = exports.worldsController = exports.battleController = exports.marchingController = exports.enemyController = exports.trainningController = exports.upgradeController = exports.unitController = exports.buildingController = exports.resourceController = exports.userController = exports.authController = void 0;
var authController_1 = require("./authController");
Object.defineProperty(exports, "authController", { enumerable: true, get: function () { return __importDefault(authController_1).default; } });
var userController_1 = require("./userController");
Object.defineProperty(exports, "userController", { enumerable: true, get: function () { return __importDefault(userController_1).default; } });
var resourceController_1 = require("./resourceController");
Object.defineProperty(exports, "resourceController", { enumerable: true, get: function () { return __importDefault(resourceController_1).default; } });
var buildingController_1 = require("./buildingController");
Object.defineProperty(exports, "buildingController", { enumerable: true, get: function () { return __importDefault(buildingController_1).default; } });
var unitController_1 = require("./unitController");
Object.defineProperty(exports, "unitController", { enumerable: true, get: function () { return __importDefault(unitController_1).default; } });
var upgradeController_1 = require("./upgradeController");
Object.defineProperty(exports, "upgradeController", { enumerable: true, get: function () { return __importDefault(upgradeController_1).default; } });
var trainningController_1 = require("./trainningController");
Object.defineProperty(exports, "trainningController", { enumerable: true, get: function () { return __importDefault(trainningController_1).default; } });
var enemyController_1 = require("./enemyController");
Object.defineProperty(exports, "enemyController", { enumerable: true, get: function () { return __importDefault(enemyController_1).default; } });
var marchingController_1 = require("./marchingController");
Object.defineProperty(exports, "marchingController", { enumerable: true, get: function () { return __importDefault(marchingController_1).default; } });
var battleController_1 = require("./battleController");
Object.defineProperty(exports, "battleController", { enumerable: true, get: function () { return __importDefault(battleController_1).default; } });
var worldsController_1 = require("./worldsController");
Object.defineProperty(exports, "worldsController", { enumerable: true, get: function () { return __importDefault(worldsController_1).default; } });
var clanController_1 = require("./clanController");
Object.defineProperty(exports, "clanController", { enumerable: true, get: function () { return __importDefault(clanController_1).default; } });
var marketController_1 = require("./marketController");
Object.defineProperty(exports, "marketController", { enumerable: true, get: function () { return __importDefault(marketController_1).default; } });
var castleController_1 = require("./castleController");
Object.defineProperty(exports, "castleController", { enumerable: true, get: function () { return __importDefault(castleController_1).default; } });
