"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Castles = exports.Markets = exports.ClanRequests = exports.Clans = exports.Worlds = exports.BattleActions = exports.BattleRounds = exports.Battles = exports.Marchings = exports.Trainnings = exports.Units = exports.UnitDatas = exports.Resources = exports.ResourceDatas = exports.Buildings = exports.BuildingDatas = exports.Users = void 0;
var Users_1 = require("./Users");
Object.defineProperty(exports, "Users", { enumerable: true, get: function () { return Users_1.default; } });
var BuildingDatas_1 = require("./BuildingDatas");
Object.defineProperty(exports, "BuildingDatas", { enumerable: true, get: function () { return BuildingDatas_1.default; } });
var Buildings_1 = require("./Buildings");
Object.defineProperty(exports, "Buildings", { enumerable: true, get: function () { return Buildings_1.default; } });
var ResourceDatas_1 = require("./ResourceDatas");
Object.defineProperty(exports, "ResourceDatas", { enumerable: true, get: function () { return ResourceDatas_1.default; } });
var Resources_1 = require("./Resources");
Object.defineProperty(exports, "Resources", { enumerable: true, get: function () { return Resources_1.default; } });
var UnitDatas_1 = require("./UnitDatas");
Object.defineProperty(exports, "UnitDatas", { enumerable: true, get: function () { return UnitDatas_1.default; } });
var Units_1 = require("./Units");
Object.defineProperty(exports, "Units", { enumerable: true, get: function () { return Units_1.default; } });
var Trainnings_1 = require("./Trainnings");
Object.defineProperty(exports, "Trainnings", { enumerable: true, get: function () { return Trainnings_1.default; } });
var Marchings_1 = require("./Marchings");
Object.defineProperty(exports, "Marchings", { enumerable: true, get: function () { return Marchings_1.default; } });
var Battles_1 = require("./Battles");
Object.defineProperty(exports, "Battles", { enumerable: true, get: function () { return Battles_1.default; } });
var BattleRounds_1 = require("./BattleRounds");
Object.defineProperty(exports, "BattleRounds", { enumerable: true, get: function () { return BattleRounds_1.default; } });
var BattleActions_1 = require("./BattleActions");
Object.defineProperty(exports, "BattleActions", { enumerable: true, get: function () { return BattleActions_1.default; } });
var Worlds_1 = require("./Worlds");
Object.defineProperty(exports, "Worlds", { enumerable: true, get: function () { return Worlds_1.default; } });
var Clans_1 = require("./Clans");
Object.defineProperty(exports, "Clans", { enumerable: true, get: function () { return Clans_1.default; } });
var ClanRequests_1 = require("./ClanRequests");
Object.defineProperty(exports, "ClanRequests", { enumerable: true, get: function () { return ClanRequests_1.default; } });
var Markets_1 = require("./Markets");
Object.defineProperty(exports, "Markets", { enumerable: true, get: function () { return Markets_1.default; } });
var Castles_1 = require("./Castles");
Object.defineProperty(exports, "Castles", { enumerable: true, get: function () { return Castles_1.default; } });
//# sourceMappingURL=index.js.map